# Generated by Django 5.1.3 on 2024-12-17 05:43

import reservasAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.PositiveIntegerField(validators=[reservasAPP.models.validar_cantidad_personas])),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO_ASISTEN', 'No Asisten')], default='RESERVADO', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
